title: Merging With the Source
author: Jeremy Harding
email: j.harding6317@edmail.edcc.edu
description: > Words about waves. Celebrations about programming. Japan is future.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  whatdoesthismean # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
